build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-addon-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-addon-base:latest"
  armv7: "ghcr.io/home-assistant/armv7-addon-base:latest"
  armhf: "ghcr.io/home-assistant/armhf-addon-base:latest"

