build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base:8.2.0
  amd64: ghcr.io/hassio-addons/ubuntu-base:8.2.0
  armv7: ghcr.io/hassio-addons/ubuntu-base:8.2.0
  armhf: ghcr.io/hassio-addons/ubuntu-base:8.2.0


