build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-addon-base:17.0.1"
  amd64: "ghcr.io/home-assistant/amd64-addon-base:17.0.1"
  armv7: "ghcr.io/home-assistant/armv7-addon-base:17.0.1"
  armhf: "ghcr.io/home-assistant/armhf-addon-base:17.0.1"

